name:                elm-language-server
version:             0.1.0.0
github:              "elm-tooling/elm-language-server"
license:             BSD3
author:              "Martin Norbäck Olivers"
maintainer:          "martin@norpan.org"
copyright:           "2018 Martin Norbäck Olivers"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/elm-tooling/elm-language-server#README.md>

dependencies:
  - Glob
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - data-default
  - directory
  - elm
  - elm-format
  - filepath
  - haskell-lsp
  - haskell-lsp-types
  - hslogger
  - lens >= 4.15.2
  - mtl
  - network-uri
  - parsec
  - stm
  - text
  - time
  - transformers
  - unordered-containers
  - vector
  - yi-rope
  - optparse-applicative # for parsing commandline arguments

library:
  source-dirs:
    - src

executables:
  elm-language-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-language-server

tests:
  elm-language-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-language-server
