version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-11.22
    steps:
      - checkout
      - run:
          name: Pull Git Submodules
          command: git submodule sync --recursive && git submodule update --recursive --init
      - run:
          name: Setup
          command: stack setup
      - run:
          name: Install
          command: stack install
